#!/bin/sh

set -e

case "$1" in
    configure)
        # Create user account for dropping privileges to run openconnect.
        systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} nm-openconnect-sysusers.conf
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown arguments \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
